"use client";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import { BarChart3, ChevronRight, CircleHelp, House, Landmark, RefreshCw, ShieldCheck, TrendingUp, Users, Wallet, X } from "lucide-react";
import { colors, countries, emptyPortfolio, summarize, validatePortfolio, type Portfolio } from "@/lib/family/model";

import AnnualPerformance from "./AnnualPerformance";

const money=(n:number)=>Math.round(n).toLocaleString("ko-KR");
const won=(n:number)=>money(n)+"원";
const pct=(n:number|null)=>n===null?"자료 확인 필요":(n*100).toFixed(1)+"%";
const signed=(n:number|null)=>n===null?"자료 확인 필요":(n>=0?"+":"−")+won(Math.abs(n));
const today=()=>new Date().toISOString().slice(0,10);
type Tab="overview"|"performance"|"allocation"|"flows"|"family";
export default function FamilyDashboard(){
 const [data,setData]=useState<Portfolio>(emptyPortfolio),[ready,setReady]=useState(false),[owner,setOwner]=useState("all"),[account,setAccount]=useState("all"),[broker,setBroker]=useState("all"),[tab,setTab]=useState<Tab>("overview");
 const [notice,setNotice]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[updatedAt,setUpdatedAt]=useState("");
 const revision=useRef(""),reading=useRef(false),quoting=useRef(false);
 const loadOnline=useCallback(async (quiet=false)=>{
  if(quoting.current||reading.current)return;
  reading.current=true;
  try{const r=await fetch("/api/family-data",{cache:"no-store",signal:AbortSignal.timeout(20000)});if(r.status===401){window.location.replace("/");return;}const result=await r.json();if(!r.ok)throw Error(result.error||"자료를 불러오지 못했어요.");const p=validatePortfolio(result.data);if(quoting.current)return;if(result.revision!==revision.current){revision.current=result.revision;setData(p);}setUpdatedAt(result.updated_at);setReady(true);if(!quiet){setError("");setNotice("온라인 자료를 불러왔어요.");}}
  catch(e){setError(e instanceof Error?e.message:"온라인 저장소에 연결하지 못했어요.");}finally{reading.current=false;}
 },[]);
 useEffect(()=>{const start=setTimeout(()=>void loadOnline(true),0);const sync=()=>{if(document.visibilityState==="visible")void loadOnline(true);};const timer=setInterval(sync,30000);window.addEventListener("focus",sync);return()=>{clearTimeout(start);clearInterval(timer);window.removeEventListener("focus",sync);};},[loadOnline]);
 async function logout(){try{const r=await fetch("/api/family-session",{method:"DELETE"});if(!r.ok)throw Error();window.location.replace("/");}catch{setError("잠금 요청에 실패했어요. 다시 시도해 주세요.");}}
 const s=summarize(data,owner,account,broker);
 const name=(id:string)=>data.owners.find(o=>o.id===id)?.name||"가족";
 const accountName=(id:string)=>data.accounts.find(a=>a.id===id)?.name||id;
 const selectOwner=(id:string)=>{setOwner(id);setAccount("all");setBroker("all");};
 async function refresh(){if(quoting.current||reading.current)return;quoting.current=true;setBusy(true);setError("");setNotice("");try{const codes=[...new Set(data.holdings.map(h=>h.code))];if(!codes.length)throw Error("등록된 보유상품이 없어요. 자료를 ChatGPT에 올려 주세요.");const r=await fetch("/api/family-quotes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbols:codes}),signal:AbortSignal.timeout(45000)});if(r.status===401){window.location.replace("/");return;}const result=await r.json();if(!r.ok)throw Error(result.error||"시세를 불러오지 못했습니다.");const products={...data.products};for(const code of codes)if(Number.isFinite(result.prices[code])&&result.prices[code]>0)products[code]={...products[code],price:result.prices[code]};const missing=codes.filter(c=>!result.prices[c]);if(missing.length)throw Error(`시세 누락: ${missing.join(", ")}. 가격이 섞이지 않도록 이전 평가를 유지했어요.`);setData({...data,products,checkedAt:result.checkedAt,pricedAt:today()});setNotice("화면의 시세를 갱신했어요. 보유수량·현금은 자료 기준일 그대로입니다.");}catch(e){setError(e instanceof Error?e.message:"시세 조회에 실패했습니다.");}finally{quoting.current=false;setBusy(false);}}
 const title=account!=="all"?accountName(account):owner==="all"?"가족 전체 자산":name(owner)+"의 자산";
 if(!ready)return <main className="boot"><section><p>{error||"온라인 자산을 불러오고 있어요…"}</p>{error&&<button className="button primary" onClick={()=>void loadOnline()}>다시 불러오기</button>}</section></main>;
 return <div className="family-app">
  <aside className="family-sidebar"><Link className="family-brand" href="/"><span className="brand-symbol"><House size={23}/></span><span>우리집 자산<small>FAMILY PORTFOLIO</small></span></Link><p className="nav-label">함께 모으는 우리의 미래</p><nav aria-label="계좌주 선택"><button className={owner==="all"?"owner active":"owner"} onClick={()=>selectOwner("all")}><span className="avatar"><Users size={17}/></span>가족 전체</button>{data.owners.map((o,i)=><button key={o.id} className={owner===o.id?"owner active":"owner"} onClick={()=>selectOwner(o.id)}><span className={`avatar tone-${i%4}`}>{o.name.slice(0,1)}</span>{o.name}{!data.accounts.some(a=>a.owner===o.id)&&<small>미등록</small>}</button>)}</nav><button className="sidebar-manage" onClick={()=>setTab("family")}><Users size={16}/> 가족·계좌</button><div className="sidebar-bottom"><ShieldCheck size={18}/><strong>온라인 보관함</strong><p>모든 기기에서 같은 자료를 확인해요.<br/>{updatedAt&&`최근 저장 ${new Date(updatedAt).toLocaleString("ko-KR")}`}</p><button className="text-button" onClick={()=>void logout()} disabled={busy}>보관함 잠그기</button></div></aside>
  <main className="family-main"><header className="family-top"><div><p className="eyebrow">OUR FAMILY, OUR FUTURE</p><h1>{title}</h1><p className="subtitle">흩어진 계좌를 한곳에, 가족의 자산을 한눈에.</p></div><div className="top-actions"><button className="button soft" disabled={busy} onClick={()=>void loadOnline()}>최신 자료</button><button className="button soft mobile-lock" disabled={busy} onClick={()=>void logout()}>잠금</button><button className="button primary" onClick={refresh} disabled={busy||!data.holdings.length}><RefreshCw size={16} className={busy?"spin":""}/>{busy?"조회 중…":"시세 갱신"}</button></div></header>
  <div className="filterbar"><label className="mobile-owner">계좌주<select value={owner} onChange={e=>selectOwner(e.target.value)}><option value="all">가족 전체</option>{data.owners.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>증권사<select value={broker} onChange={e=>{setBroker(e.target.value);setAccount("all");}}><option value="all">모든 증권사</option>{[...new Set(data.accounts.filter(a=>owner==="all"||a.owner===owner).map(a=>a.broker))].map(b=><option key={b}>{b}</option>)}</select></label><label>계좌<select value={account} onChange={e=>setAccount(e.target.value)}><option value="all">전체 계좌</option>{data.accounts.filter(a=>(owner==="all"||a.owner===owner)&&(broker==="all"||a.broker===broker)).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><span className="date-badge">자료 기준 {data.asOf.replaceAll("-",".")}</span></div>
  {error&&<div className="message error" role="alert">{error}<button aria-label="오류 닫기" onClick={()=>setError("")}><X size={17}/></button></div>}{notice&&<div className="message" role="status">{notice}<button aria-label="안내 닫기" onClick={()=>setNotice("")}><X size={17}/></button></div>}
  <nav className="view-tabs" aria-label="자산 보기">{([["overview","자산 현황",Wallet],["performance","연도별 수익률",TrendingUp],["allocation","국가별 배분",BarChart3],["flows","입출금 내역",Landmark],["family","가족·계좌",Users]] as const).map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} aria-current={tab===id?"page":undefined}><Icon size={17}/>{label}</button>)}</nav>
  {tab!=="family"&&s.selected.length===0?<section className="welcome"><div className="welcome-icon"><Wallet size={32}/></div><span className="eyebrow">처음부터, 우리 가족에게 맞게</span><h2>{data.accounts.length?`${owner==="all"?"선택한 범위":name(owner)}의 자료가 아직 없어요`:"우리 가족의 자산 기록을 시작하세요"}</h2><p>계좌 자료를 ChatGPT 대화에 올려 주세요.<br/>정리·반영된 자산을 이곳에서 확인할 수 있어요.</p><div className="welcome-features"><span><Users/>가족·증권사별 구분</span><span><BarChart3/>현금흐름 기반 XIRR</span><span><ShieldCheck/>온라인에 안전하게 저장</span></div><p className="fine">자료가 없는 가족은 0원으로 집계하지 않습니다.</p></section>:<>
  {s.selected.some(a=>a.valuationDate)&&<div className="quiet-note"><CircleHelp size={16}/><span>{s.selected.filter(a=>a.valuationDate).map(a=>`${name(a.owner)} ${a.name}: ${a.valuationDate} 최종 확인 잔고${a.cashLabel?` (${a.cashLabel})`:""}`).join(" · ")}. 이후 이자·거래는 미반영이며 총자산·수익률은 최근 확인 금액 기준 추정치입니다.</span></div>}
  {tab==="overview"&&<><div className="headline-grid"><section className="wealth-card"><div className="card-kicker">{s.missing?"평가 가능한 투자자산":"총 투자자산"}<span>{s.selected.length}개 계좌</span></div><div className="wealth-number">{money(s.nav)}<small>원</small></div><div className="wealth-bottom"><span>누적 투자손익</span><strong>{signed(s.profit)}</strong></div><span className="card-decoration" aria-hidden="true"/></section><section className="return-card"><div className="card-kicker">연환산 수익률 <span>XIRR</span></div><div className={s.xirr===null?"return-number unavailable":"return-number"}>{pct(s.xirr)}</div><p>입출금 날짜와 금액을 반영한 수익률</p><div className="return-bottom"><span>순납입액</span><strong>{s.complete?won(s.net):"입출금 확인 필요"}</strong></div></section></div>
  {(!s.complete||data.pricedAt)&&<div className="quiet-note"><CircleHelp size={16}/><span>{!s.complete?"입출금 이력 확인 또는 미평가 상품의 가격이 필요해요. 누락된 자료를 ChatGPT에 올려 주세요.":`보유수량·현금은 ${data.asOf} 자료이며, 가격만 갱신한 추정 자산입니다. 이후 거래가 있다면 먼저 반영해 주세요.`}</span></div>}
  <div className="section-title"><h2>계좌별 자산</h2></div><div className="account-grid">{s.selected.map(a=>{const sub=summarize(data,"all",a.id);return <button className="account-card" key={a.id} onClick={()=>setAccount(a.id)}><div className="account-heading"><span className="broker-mark">{a.broker.slice(0,2)}</span><div><strong>{a.name}</strong><small>{name(a.owner)} · {a.broker}</small></div><ChevronRight size={16}/></div><div className="account-amount">{money(sub.nav)}<small>원</small></div><div className="account-foot"><span>{a.type}</span><strong>{pct(sub.xirr)}</strong></div></button>;})}</div>
  <div className="two-column"><section className="surface"><div className="section-title"><h2>자산 구성</h2><span>기초자산 기준</span></div><div className="asset-bar">{[[s.equity,colors[0]],[s.exposure[4],colors[1]],[Math.max(0,s.cash),"#c7d2e3"]].map(([v,c],i)=><i key={i} style={{width:`${s.nav>0?Number(v)/s.nav*100:0}%`,background:String(c)}}/>)}</div>{[["주식",s.equity,colors[0]],["채권",s.exposure[4],colors[1]],["현금·CMA",s.cash,"#c7d2e3"]].map(([label,value,color])=><div className="legend" key={String(label)}><span><i style={{background:String(color)}}/>{label}</span><span>{won(Number(value))}<strong>{s.nav>0?(Number(value)/s.nav*100).toFixed(1)+"%":"—"}</strong></span></div>)}</section><section className="surface"><div className="section-title"><h2>투자손익 살펴보기</h2></div>{[["평가손익",s.missing?null:s.positions.reduce((t,h)=>t+(h.profit??0),0)],["실현손익",s.selected.reduce((t,a)=>t+a.realized,0)],["받은 배당금",s.selected.reduce((t,a)=>t+a.div,0)],["받은 이자",s.selected.some(a=>a.interestKnown===false)?null:s.selected.reduce((t,a)=>t+a.interest,0)]].map(([label,value])=><div className="legend" key={String(label)}><span>{label}</span><strong className={Number(value)<0?"negative":"positive"}>{value===null?(label==="받은 이자"?"별도 집계 미확인":"미평가"):won(Number(value))}</strong></div>)}</section></div>
  <section className="surface holdings"><div className="section-title"><h2>보유상품 <em>{s.positions.length}</em></h2><span>{data.checkedAt?`시세 조회 ${new Date(data.checkedAt).toLocaleString("ko-KR")}`:"파일 기준가격 · 실시간 아님"}</span></div><div className="table-wrap"><table><thead><tr><th>상품 / 계좌</th><th>보유수량</th><th>평가액</th><th>평가손익</th></tr></thead><tbody>{s.positions.map(h=><tr key={h.account+h.code}><td><strong>{h.name}</strong><small>{name(data.accounts.find(a=>a.id===h.account)!.owner)} · {accountName(h.account)} · {h.code}</small></td><td>{h.quantity.toLocaleString("ko-KR")}주<small>평균 {won(h.cost/h.quantity)}</small></td><td><strong>{h.value===null?"가격 필요":won(h.value)}</strong><small>{h.price===null?"—":"기준가격 "+won(h.price)}</small></td><td className={(h.profit??0)<0?"negative":"positive"}>{h.profit===null?"미평가":signed(h.profit)}<small>{h.cost&&h.profit!==null?(h.profit/h.cost*100).toFixed(1)+"%":"—"}</small></td></tr>)}</tbody></table></div>{!s.positions.length&&<p className="fine">등록된 보유상품이 없습니다.</p>}</section></>}
  {tab==="performance"&&<AnnualPerformance data={data} owner={owner} account={account} broker={broker}/>}
  {tab==="allocation"&&<><div className="two-column"><section className="surface"><div className="section-title"><h2>주식의 국가별 비중</h2><span>채권·현금 제외</span></div><div className="donut"><svg viewBox="0 0 120 120" role="img" aria-label={countries.map((c,i)=>`${c} ${s.equity?(s.exposure[i]/s.equity*100).toFixed(1):0}%`).join(", ")}><circle cx="60" cy="60" r="48" fill="none" stroke="#edf0f5" strokeWidth="10"/>{countries.map((_,i)=>{const portion=s.equity?s.exposure[i]/s.equity*100:0,offset=s.equity?s.exposure.slice(0,i).reduce((a,b)=>a+b,0)/s.equity*100:0;return <circle key={i} cx="60" cy="60" r="48" fill="none" stroke={colors[i]} strokeWidth="10" pathLength="100" strokeDasharray={`${portion} ${100-portion}`} strokeDashoffset={-offset}/>;})}</svg><div><small>주식 투자금액</small><strong>{money(s.equity/10000)}만 원</strong></div></div>{countries.map((c,i)=><div className="legend" key={c}><span><i style={{background:colors[i]}}/>{c}</span><span>{won(s.exposure[i])}<strong>{s.equity?(s.exposure[i]/s.equity*100).toFixed(1)+"%":"—"}</strong></span></div>)}</section><section className="surface"><div className="section-title"><h2>목표비중과 비교</h2><span>주식 총액 기준</span></div><p className="fine">ChatGPT에서 정리한 목표비중과 현재 비중을 비교해요. 목표 변경은 대화에서 요청해 주세요.</p><div className="target-results">{countries.map((c,i)=>{const delta=s.equity*data.targets[i]/100-s.exposure[i];return <div className="legend" key={c}><span>{c} <small>{data.targets[i]}% 목표</small></span><strong>{s.equity?won(Math.abs(delta))+(delta>0?" 부족":delta<0?" 초과":" 일치"):"—"}</strong></div>;})}</div><p className="fine">저장된 목표를 기준으로 계산합니다. 조정금액은 주식 총액을 유지하는 계산이며 매매 추천이 아닙니다.</p></section></div><div className="quiet-note"><CircleHelp size={17}/><span>국가는 상장 거래소가 아닌 실제 투자대상 기준입니다. 혼합 ETF는 입력한 주식·채권 비율로 나눕니다. 한국주식 50%·미국채 50% 설정은 목표배분 근사이며 일별 비중과 다를 수 있습니다.</span></div></>}
  {tab==="flows"&&<section className="surface"><div className="section-title"><h2>계좌 밖에서 들어오고 나간 돈</h2></div><p className="fine">입금은 투자자의 현금유출(-), 출금은 회수(+)입니다. 매수·매도·계좌 안의 배당은 XIRR 현금흐름에 중복 반영하지 않습니다.</p><div className="table-wrap"><table><thead><tr><th>날짜</th><th>가족 / 계좌</th><th>구분</th><th>금액</th></tr></thead><tbody>{[...s.movements].sort((a,b)=>b.date.localeCompare(a.date)).map(f=><tr key={f.id}><td>{f.date}</td><td>{name(data.accounts.find(a=>a.id===f.account)!.owner)}<small>{accountName(f.account)}</small></td><td><span className="tag">{f.transfer?"내부이체 · ":""}{f.amount<0?"입금":"출금"}</span></td><td>{won(Math.abs(f.amount))}</td></tr>)}</tbody></table></div>{!s.movements.length&&<p className="fine">입출금 이력을 등록하면 XIRR을 계산할 수 있어요.</p>}</section>}
  {tab==="family"&&<><div className="manage-intro surface"><ShieldCheck size={25}/><div><h2>우리 가족의 자산 보관함</h2><p>자료는 ChatGPT 대화에 올리고, 반영된 결과는 이곳에서 확인해요. 가족·계좌·목표비중 변경도 대화에서 요청해 주세요.</p></div></div><div className="section-title"><h2>가족 구성원</h2></div><div className="owner-grid">{data.owners.map((o,i)=><button className="family-person" key={o.id} onClick={()=>{selectOwner(o.id);setTab("overview");}}><span className={`avatar tone-${i%4}`}>{o.name.slice(0,1)}</span><strong>{o.name}</strong><small>{data.accounts.filter(a=>a.owner===o.id).length?data.accounts.filter(a=>a.owner===o.id).length+"개 계좌":"자료 없음"}</small></button>)}</div><section className="surface"><div className="section-title"><h2>계좌 정보</h2><span>자료 기준 {data.asOf}</span></div><div className="table-wrap"><table><thead><tr><th>가족 / 계좌</th><th>증권사 / 유형</th><th>현금·CMA</th><th>입출금 이력</th></tr></thead><tbody>{data.accounts.filter(a=>(owner==="all"||a.owner===owner)&&(broker==="all"||a.broker===broker)&&(account==="all"||a.id===account)).map(a=><tr key={a.id}><td><strong>{a.name}</strong><small>{name(a.owner)} · {a.mask}</small></td><td>{a.broker}<small>{a.type}</small></td><td>{won(a.cash)}{a.cashLabel&&<small>{a.cashLabel}</small>}{a.valuationDate&&<small>잔고 확인 {a.valuationDate}</small>}</td><td>{a.complete?"확인 완료":"자료 확인 필요"}</td></tr>)}</tbody></table></div></section></>}
  </>}
  <details className="method"><summary>자료 반영과 계산 방법</summary><p>엑셀·거래내역은 ChatGPT 대화에 첨부해 주세요. 내용을 확인하고 온라인 저장소에 반영한 후 이 화면에 표시됩니다. 이 사이트는 조회 전용이며, 파일 업로드나 자료 수정은 지원하지 않습니다.</p><p>XIRR은 입금(-), 출금(+), 평가일 자산(+)으로 다시 계산하며 계좌별 수익률을 평균하지 않습니다. 연결된 내부이체는 두 계좌가 모두 선택되면 제외하고, 하나만 선택하면 입출금에 반영합니다. 모든 자료는 원화 기준입니다. 누락된 현금흐름, 여러 해가 나오는 계산, 평가 불가 상품은 수익률을 확정하지 않습니다.</p><p>시세 갱신은 종목코드만 서버로 보내 Yahoo 시세와 조회 환율을 가져옵니다. 시세는 현재 화면에만 적용하며 저장된 자료는 변경하지 않습니다. 지연 가격일 수 있으며 수량·현금·계좌내역은 자동 연동하지 않습니다. 수수료·세금 등은 제공한 원가와 현금에 반영된 범위만 포함합니다.</p></details>
  <footer className="family-footer"><span>우리집 자산</span><span>함께 쌓아가는 가족의 미래</span></footer></main>
 </div>;
}
