"use client";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import { ArrowDownWideNarrow, ArrowUpNarrowWide, BarChart3, ChevronRight, CircleHelp, House, Landmark, Pencil, RefreshCw, ShieldCheck, TrendingUp, Users, Wallet, X } from "lucide-react";
import { accountGroup, accountGroupName, accountGroups, colors, countries, emptyPortfolio, summarize, targetLabels, validatePortfolio, type Portfolio } from "@/lib/family/model";
import { allocationBreakdown, consolidateHoldings, sortHoldings, targetActuals, type HoldingSort } from "@/lib/family/breakdown";

import AnnualPerformance from "./AnnualPerformance";
import PerformanceCard from "./PerformanceCard";

const money=(n:number)=>Math.round(n).toLocaleString("ko-KR");
const won=(n:number)=>money(n)+"원";
const pct=(n:number|null)=>n===null?"자료 확인 필요":(n*100).toFixed(1)+"%";
const signed=(n:number|null)=>n===null?"자료 확인 필요":(n>=0?"+":"−")+won(Math.abs(n));
const today=()=>new Date().toISOString().slice(0,10);
type Tab="overview"|"performance"|"allocation"|"flows";
const share=(v:number,total:number)=>total>0?(v/total*100).toFixed(1)+"%":"—";
const currencyNames:Record<string,string>={KRW:"원화",USD:"달러",JPY:"엔화",CNY:"위안화",HKD:"홍콩달러",EUR:"유로"};
const currencyUnits:Record<string,string>={JPY:"엔",USD:"달러",CNY:"위안",EUR:"유로",HKD:"홍콩달러"};
const currencyColors:Record<string,string>={KRW:colors[0],USD:colors[2],JPY:"#e39a4c",CNY:colors[1],HKD:"#5fb8c9",EUR:"#d77a9a"};
const sortOptions:[HoldingSort,string][]=[["value","평가액"],["profit","수익금"],["rate","수익률"]];
export default function FamilyDashboard(){
 const [data,setData]=useState<Portfolio>(emptyPortfolio),[ready,setReady]=useState(false),[owner,setOwner]=useState("all"),[account,setAccount]=useState("all"),[broker,setBroker]=useState("all"),[tab,setTab]=useState<Tab>("overview"),[group,setGroup]=useState("all");
 const [sortKey,setSortKey]=useState<HoldingSort>("value"),[descending,setDescending]=useState(true),[draft,setDraft]=useState<string[]|null>(null),[saving,setSaving]=useState(false);
 const [notice,setNotice]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[updatedAt,setUpdatedAt]=useState("");
 const revision=useRef(""),reading=useRef(false),quoting=useRef(false);
 const loadOnline=useCallback(async (quiet=false)=>{
  if(quoting.current||reading.current)return;
  reading.current=true;
  try{const r=await fetch("/api/family-data",{cache:"no-store",signal:AbortSignal.timeout(20000)});if(r.status===401){window.location.replace("/");return;}const result=await r.json();if(!r.ok)throw Error(result.error||"자료를 불러오지 못했어요.");const p=validatePortfolio(result.data);if(quoting.current)return;if(result.revision!==revision.current){revision.current=result.revision;setData(p);}setUpdatedAt(result.updated_at);setReady(true);if(!quiet){setError("");setNotice("온라인 자료를 불러왔어요.");}}
  catch(e){setError(e instanceof Error?e.message:"온라인 저장소에 연결하지 못했어요.");}finally{reading.current=false;}
 },[]);
 useEffect(()=>{const start=setTimeout(()=>void loadOnline(true),0);const sync=()=>{if(document.visibilityState==="visible")void loadOnline(true);};const timer=setInterval(sync,30000);window.addEventListener("focus",sync);return()=>{clearTimeout(start);clearInterval(timer);window.removeEventListener("focus",sync);};},[loadOnline]);
 const s=summarize(data,owner,account,broker,group);
 const holdings=sortHoldings(consolidateHoldings(s),sortKey,descending),breakdown=allocationBreakdown(data,s),actual=targetActuals(s);
 const fixedTotal=breakdown.fixed.reduce((t,v)=>t+v,0),cashTotal=breakdown.cash.reduce((t,[,v])=>t+v,0);
 const draftTotal=draft?draft.reduce((t,v)=>t+(Number(v)||0),0):100,draftValid=!!draft&&draft.every(v=>v.trim()!==""&&Number.isFinite(Number(v))&&Number(v)>=0&&Number(v)<=100)&&Math.abs(draftTotal-100)<.001;
 const name=(id:string)=>data.owners.find(o=>o.id===id)?.name||"가족";
 const accountName=(id:string)=>data.accounts.find(a=>a.id===id)?.name||id;
 const selectOwner=(id:string)=>{setOwner(id);setAccount("all");setBroker("all");};
 const accountOptions=data.accounts.filter(a=>(owner==="all"||a.owner===owner)&&(broker==="all"||a.broker===broker)&&(group==="all"||accountGroup(a.type)===group));
 const unit=(code:string)=>{const p=data.products[code];return p.kind==="cash"?(currencyUnits[p.currency!]||" "+p.currency):"주";};
 /** Foreign cash is quoted like a bank rate: 원 per 100엔, 원 per 1달러. */
 const unitPrice=(code:string,krw:number)=>{const p=data.products[code];if(p.kind!=="cash")return won(krw);const per=p.currency==="JPY"?100:1;return (krw*per).toLocaleString("ko-KR",{maximumFractionDigits:2})+"원/"+(per===100?"100":"")+unit(code).trim();};
 const groupLabel=accountGroups.find(([id])=>id===group)?.[1];
 async function saveTargets(){if(!draft||!draftValid||saving)return;setSaving(true);setError("");setNotice("");try{const r=await fetch("/api/family-targets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({targets:draft.map(Number),revision:revision.current}),signal:AbortSignal.timeout(20000)});if(r.status===401){window.location.replace("/");return;}const result=await r.json();if(!r.ok){if(r.status===409)void loadOnline(true);throw Error(result.error||"목표비중을 저장하지 못했어요.");}revision.current=result.revision;setData(d=>({...d,targets:result.targets,targetsBasis:"nav"}));setUpdatedAt(result.updated_at);setDraft(null);setNotice("목표비중을 저장했어요. 모든 기기에 반영됩니다.");}catch(e){setError(e instanceof Error?e.message:"목표비중을 저장하지 못했어요.");}finally{setSaving(false);}}
 async function refresh(){if(quoting.current||reading.current)return;quoting.current=true;setBusy(true);setError("");setNotice("");try{const codes=[...new Set(data.holdings.map(h=>h.code))];if(!codes.length)throw Error("등록된 보유상품이 없어요. 자료를 ChatGPT에 올려 주세요.");const r=await fetch("/api/family-quotes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbols:codes}),signal:AbortSignal.timeout(45000)});if(r.status===401){window.location.replace("/");return;}const result=await r.json();if(!r.ok)throw Error(result.error||"시세를 불러오지 못했습니다.");const products={...data.products};for(const code of codes)if(Number.isFinite(result.prices[code])&&result.prices[code]>0)products[code]={...products[code],price:result.prices[code]};const missing=codes.filter(c=>!result.prices[c]);if(missing.length)throw Error(`시세 누락: ${missing.join(", ")}. 가격이 섞이지 않도록 이전 평가를 유지했어요.`);setData({...data,products,checkedAt:result.checkedAt,pricedAt:today()});setNotice("화면의 시세를 갱신했어요. 보유수량·현금은 자료 기준일 그대로입니다.");}catch(e){setError(e instanceof Error?e.message:"시세 조회에 실패했습니다.");}finally{quoting.current=false;setBusy(false);}}
 const title=account!=="all"?accountName(account):(owner==="all"?"가족 전체 자산":name(owner)+"의 자산")+(groupLabel?" · "+groupLabel:"");
 if(!ready)return <main className="boot"><section><p>{error||"온라인 자산을 불러오고 있어요…"}</p>{error&&<button className="button primary" onClick={()=>void loadOnline()}>다시 불러오기</button>}</section></main>;
 return <div className="family-app">
  <aside className="family-sidebar"><Link className="family-brand" href="/"><span className="brand-symbol"><House size={23}/></span><span>엘린하우스<small>FAMILY PORTFOLIO</small></span></Link><p className="nav-label">함께 모으는 우리의 미래</p><nav aria-label="계좌주 선택"><button className={owner==="all"?"owner active":"owner"} onClick={()=>selectOwner("all")}><span className="avatar"><Users size={17}/></span>가족 전체</button>{data.owners.map((o,i)=><button key={o.id} className={owner===o.id?"owner active":"owner"} onClick={()=>selectOwner(o.id)}><span className={`avatar tone-${i%4}`}>{o.name.slice(0,1)}</span>{o.name}{!data.accounts.some(a=>a.owner===o.id)&&<small>미등록</small>}</button>)}</nav><div className="sidebar-bottom"><ShieldCheck size={18}/><strong>온라인 보관함</strong><p>모든 기기에서 같은 자료를 확인해요.<br/>{updatedAt&&`최근 저장 ${new Date(updatedAt).toLocaleString("ko-KR")}`}</p></div></aside>
  <main className="family-main"><header className="family-top"><div><p className="eyebrow">OUR FAMILY, OUR FUTURE</p><h1>{title}</h1><p className="subtitle">흩어진 계좌를 한곳에, 가족의 자산을 한눈에.</p></div><div className="top-actions"><button className="button primary" onClick={refresh} disabled={busy||!data.holdings.length}><RefreshCw size={16} className={busy?"spin":""}/>{busy?"조회 중…":"시세 갱신"}</button></div></header>
  <div className="filterbar"><label className="mobile-owner">계좌주<select value={owner} onChange={e=>selectOwner(e.target.value)}><option value="all">가족 전체</option>{data.owners.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>증권사<select value={broker} onChange={e=>{setBroker(e.target.value);setAccount("all");}}><option value="all">모든 증권사</option>{[...new Set(data.accounts.filter(a=>owner==="all"||a.owner===owner).map(a=>a.broker))].map(b=><option key={b}>{b}</option>)}</select></label><label>계좌 유형<select value={group} onChange={e=>{setGroup(e.target.value);setAccount("all");}}><option value="all">모든 계좌 유형</option>{accountGroups.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>계좌<select value={account} onChange={e=>setAccount(e.target.value)}><option value="all">모든 계좌</option>{accountOptions.map(a=><option key={a.id} value={a.id}>{name(a.owner)} · {a.broker} · {a.name}</option>)}</select></label><span className="date-badge">자료 기준 {data.asOf.replaceAll("-",".")}</span></div>
  {error&&<div className="message error" role="alert">{error}<button aria-label="오류 닫기" onClick={()=>setError("")}><X size={17}/></button></div>}{notice&&<div className="message" role="status">{notice}<button aria-label="안내 닫기" onClick={()=>setNotice("")}><X size={17}/></button></div>}
  <nav className="view-tabs" aria-label="자산 보기">{([["overview","자산 현황",Wallet],["performance","연도별 수익률",TrendingUp],["allocation","국가별 배분",BarChart3],["flows","입출금 내역",Landmark]] as const).map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} aria-current={tab===id?"page":undefined}><Icon size={17}/>{label}</button>)}</nav>
  {s.selected.length===0?<section className="welcome"><div className="welcome-icon"><Wallet size={32}/></div><span className="eyebrow">처음부터, 우리 가족에게 맞게</span><h2>{data.accounts.length?`${owner==="all"?"선택한 범위":name(owner)}의 자료가 아직 없어요`:"우리 가족의 자산 기록을 시작하세요"}</h2><p>계좌 자료를 ChatGPT 대화에 올려 주세요.<br/>정리·반영된 자산을 이곳에서 확인할 수 있어요.</p><div className="welcome-features"><span><Users/>가족·증권사별 구분</span><span><BarChart3/>현금흐름 기반 XIRR</span><span><ShieldCheck/>온라인에 안전하게 저장</span></div><p className="fine">자료가 없는 가족은 0원으로 집계하지 않습니다.</p></section>:<>
  {s.selected.some(a=>a.valuationDate)&&<div className="quiet-note"><CircleHelp size={16}/><span>{s.selected.filter(a=>a.valuationDate).map(a=>`${name(a.owner)} ${a.name}: ${a.valuationDate} 최종 확인 잔고${a.cashLabel?` (${a.cashLabel})`:""}`).join(" · ")}. 이후 이자·거래는 미반영이며 총자산·수익률은 최근 확인 금액 기준 추정치입니다.</span></div>}
  {tab==="overview"&&<><div className="headline-grid"><section className="wealth-card"><div className="card-kicker">{s.missing?"평가 가능한 투자자산":"총 투자자산"}<span>{s.selected.length}개 계좌</span></div><div className="wealth-number">{money(s.nav)}<small>원</small></div><div className="wealth-bottom"><span>누적 투자손익</span><strong>{signed(s.profit)}</strong></div><span className="card-decoration" aria-hidden="true"/></section><section className="return-card"><div className="card-kicker">연환산 수익률 <span>XIRR</span></div><div className={s.xirr===null?"return-number unavailable":"return-number"}>{pct(s.xirr)}</div><p>입출금 날짜와 금액을 반영한 수익률</p><div className="return-bottom"><span>순납입액</span><strong>{s.complete?won(s.net):"입출금 확인 필요"}</strong></div></section></div>
  {(!s.complete||data.pricedAt)&&<div className="quiet-note"><CircleHelp size={16}/><span>{!s.complete?"입출금 이력 확인 또는 미평가 상품의 가격이 필요해요. 누락된 자료를 ChatGPT에 올려 주세요.":`보유수량·현금은 ${data.asOf} 자료이며, 가격만 갱신한 추정 자산입니다. 이후 거래가 있다면 먼저 반영해 주세요.`}</span></div>}
  <PerformanceCard data={data} owner={owner} account={account} broker={broker} group={group}/>
  <div className="section-title"><h2>계좌별 자산</h2></div><div className="account-grid">{s.selected.map(a=>{const sub=summarize(data,"all",a.id);return <button className="account-card" key={a.id} onClick={()=>setAccount(a.id)}><div className="account-heading"><span className="broker-mark">{a.broker.slice(0,2)}</span><div><strong>{a.name}</strong><small>{name(a.owner)} · {a.broker}</small></div><ChevronRight size={16}/></div><div className="account-amount">{money(sub.nav)}<small>원</small></div><div className="account-foot"><span>{accountGroupName(a.type)} · 누적손익</span><strong className={sub.profit===null?"":sub.profit<0?"negative":"positive"}>{signed(sub.profit)}</strong></div></button>;})}</div>
  <div className="two-column"><section className="surface"><div className="section-title"><h2>자산 구성</h2><span>기초자산 기준</span></div><div className="asset-bar">{[[s.equity,colors[0]],[fixedTotal,colors[1]],[Math.max(0,cashTotal),"#c7d2e3"]].map(([v,c],i)=><i key={i} style={{width:`${s.nav>0?Number(v)/s.nav*100:0}%`,background:String(c)}}/>)}</div>{[["주식",s.equity,colors[0]],["채권·예금",fixedTotal,colors[1]],["현금·CMA·외화",cashTotal,"#c7d2e3"]].map(([label,value,color])=><div className="legend" key={String(label)}><span><i style={{background:String(color)}}/>{label}</span><span>{won(Number(value))}<strong>{s.nav>0?(Number(value)/s.nav*100).toFixed(1)+"%":"—"}</strong></span></div>)}</section><section className="surface"><div className="section-title"><h2>투자손익 살펴보기</h2></div>{[["평가손익",s.missing?null:s.positions.reduce((t,h)=>t+(h.profit??0),0)],["실현손익",s.selected.reduce((t,a)=>t+a.realized,0)],["받은 배당금(세후)",s.selected.reduce((t,a)=>t+a.div,0)],["받은 이자(세후)",s.selected.some(a=>a.interestKnown===false)?null:s.selected.reduce((t,a)=>t+a.interest,0)]].map(([label,value])=><div className="legend" key={String(label)}><span>{label}</span><strong className={Number(value)<0?"negative":"positive"}>{value===null?(String(label).startsWith("받은 이자")?"별도 집계 미확인":"미평가"):won(Number(value))}</strong></div>)}</section></div>
  <section className="surface holdings"><div className="section-title"><h2>보유상품 <em>{holdings.length}</em></h2><span>{data.checkedAt?`시세 조회 ${new Date(data.checkedAt).toLocaleString("ko-KR")}`:"파일 기준가격 · 실시간 아님"}</span></div><div className="holding-sort"><div className="segmented" role="group" aria-label="정렬 기준">{sortOptions.map(([id,label])=><button key={id} aria-pressed={sortKey===id} onClick={()=>setSortKey(id)}>{label}</button>)}</div><button className="sort-direction" onClick={()=>setDescending(!descending)}>{descending?<ArrowDownWideNarrow size={15}/>:<ArrowUpNarrowWide size={15}/>}{descending?"높은순":"낮은순"}</button></div><div className="table-wrap"><table><thead><tr><th>상품 / 계좌</th><th>보유수량</th><th>평가액</th><th>수익금 / 수익률</th></tr></thead><tbody>{holdings.map(h=>{const owners=[...new Set(h.accounts.map(id=>name(data.accounts.find(a=>a.id===id)!.owner)))];return <tr key={h.code}><td><strong>{h.name}</strong><small>{h.accounts.length===1?`${owners[0]} · ${accountName(h.accounts[0])}`:`${h.accounts.length}개 계좌 · ${owners.join(", ")}`} · {h.code}</small></td><td>{h.quantity.toLocaleString("ko-KR")}{unit(h.code)}<small>평균 {unitPrice(h.code,h.cost/h.quantity)}</small></td><td><strong>{h.value===null?"가격 필요":won(h.value)}</strong><small>{h.price===null?"—":"기준가격 "+unitPrice(h.code,h.price)}</small></td><td className={(h.profit??0)<0?"negative":"positive"}>{h.profit===null?"미평가":signed(h.profit)}<small>{h.rate===null?"—":(h.rate>0?"+":"")+(h.rate*100).toFixed(1)+"%"}</small></td></tr>;})}</tbody></table></div>{!holdings.length&&<p className="fine">등록된 보유상품이 없습니다.</p>}<p className="fine">같은 상품은 계좌가 달라도 합쳐서 보여줘요. 수익률은 합친 평가손익 ÷ 합친 매입원가입니다.</p></section></>}
  {tab==="performance"&&<AnnualPerformance data={data} owner={owner} account={account} broker={broker} group={group}/>}
  {tab==="allocation"&&<><div className="two-column"><section className="surface"><div className="section-title"><h2>주식의 국가별 비중</h2><span>채권·현금 제외</span></div><div className="donut"><svg viewBox="0 0 120 120" role="img" aria-label={countries.map((c,i)=>`${c} ${s.equity?(s.exposure[i]/s.equity*100).toFixed(1):0}%`).join(", ")}><circle cx="60" cy="60" r="48" fill="none" stroke="#edf0f5" strokeWidth="10"/>{countries.map((_,i)=>{const portion=s.equity?s.exposure[i]/s.equity*100:0,offset=s.equity?s.exposure.slice(0,i).reduce((a,b)=>a+b,0)/s.equity*100:0;return <circle key={i} cx="60" cy="60" r="48" fill="none" stroke={colors[i]} strokeWidth="10" pathLength="100" strokeDasharray={`${portion} ${100-portion}`} strokeDashoffset={-offset}/>;})}</svg><div><small>주식 투자금액</small><strong>{money(s.equity/10000)}만 원</strong></div></div>{countries.map((c,i)=><div className="legend" key={c}><span><i style={{background:colors[i]}}/>{c}</span><span>{won(s.exposure[i])}<strong>{share(s.exposure[i],s.equity)}</strong></span></div>)}
  <div className="kind-breakdown"><div className="section-title"><h2>유형별 비중</h2><span>전체 자산 {won(s.nav)}</span></div>{([["ETF","국가별",breakdown.etf.map((v,i)=>[countries[i],v,colors[i]] as const)],["개별 주식","국가별",breakdown.stock.map((v,i)=>[countries[i],v,colors[i]] as const)],["채권·예금","발행 국가별",breakdown.fixed.map((v,i)=>[countries[i],v,colors[i]] as const)],["현금","통화별",breakdown.cash.map(([c,v])=>[currencyNames[c]||c,v,currencyColors[c]||colors[3]] as const)]] as const).map(([label,by,parts])=>{const total=parts.reduce((t,[,v])=>t+v,0),positive=parts.reduce((t,[,v])=>t+Math.max(0,v),0);return <div className="kind-row" key={label}><div className="kind-head"><strong>{label}<small>{by}</small></strong><span>{won(total)}<small>전체의 {share(total,s.nav)}</small></span></div><div className="asset-bar" aria-hidden="true">{parts.map(([name,v,color])=><i key={name} style={{width:`${positive>0?Math.max(0,v)/positive*100:0}%`,background:color}}/>)}</div><div className="kind-countries">{total?parts.map(([name,v,color])=>v!==0&&<span key={name}><i style={{background:color}}/>{name} <b>{share(v,total)}</b></span>):<span>보유 없음</span>}</div></div>;})}<p className="fine">혼합 ETF의 채권 부분은 채권·예금에 포함하고, 채권 국가는 상품명(예: 미국채)으로 판단합니다. 현금은 계좌별로 확인된 통화 기준이며 원화로 환산해 표시합니다.</p></div></section>
  <section className="surface"><div className="section-title"><h2>목표비중과 비교</h2>{draft?<span>전체 자산 기준</span>:<button onClick={()=>setDraft(data.targets.map(String))}><Pencil size={14}/>목표 설정</button>}</div>{draft?<form className="target-editor" onSubmit={e=>{e.preventDefault();void saveTargets();}}>{targetLabels.map((label,i)=><label className="target-row" key={label}><span><i style={{background:colors[i]}}/>{label}</span><span><input inputMode="decimal" value={draft[i]} aria-label={`${label} 목표 비중`} onChange={e=>setDraft(draft.map((v,j)=>j===i?e.target.value:v))}/>%</span></label>)}<p className={draftValid?"fine":"fine negative"}>합계 {Number(draftTotal.toFixed(2))}%{draftValid?"":" · 100%로 맞춰 주세요"}</p><div className="target-actions"><button type="button" className="button soft" onClick={()=>setDraft(null)} disabled={saving}>취소</button><button className="button primary" disabled={!draftValid||saving}>{saving?"저장 중…":"저장"}</button></div></form>:<>{data.targetsBasis!=="nav"&&<p className="fine">저장된 목표는 이전의 주식 총액 기준 값이에요. ‘목표 설정’에서 전체 자산 기준으로 다시 저장해 주세요.</p>}<div className="target-results">{targetLabels.map((label,i)=>{const delta=s.nav*data.targets[i]/100-actual[i];return <div className="legend" key={label}><span><i style={{background:colors[i]}}/>{label} <small>현재 {share(actual[i],s.nav)} · 목표 {data.targets[i]}%</small></span><strong>{s.nav>0?won(Math.abs(delta))+(Math.round(delta)>0?" 부족":Math.round(delta)<0?" 초과":" 일치"):"—"}</strong></div>;})}</div></>}<p className="fine">전체 자산(주식·채권·현금)을 기준으로 비교해요. 기타에는 현금·CMA·예금·채권과 한국·중국·미국 외 주식이 들어갑니다. 조정금액은 총자산을 유지하는 계산이며 매매 추천이 아닙니다.</p></section></div><div className="quiet-note"><CircleHelp size={17}/><span>국가는 상장 거래소가 아닌 실제 투자대상 기준입니다. 혼합 ETF는 입력한 주식·채권 비율로 나눕니다. 목표비중은 가족 모두가 같은 값을 보며, 저장해도 보유상품·현금·입출금 자료는 바뀌지 않습니다.</span></div></>}
  {tab==="flows"&&<section className="surface"><div className="section-title"><h2>계좌 밖에서 들어오고 나간 돈</h2></div><p className="fine">입금은 투자자의 현금유출(-), 출금은 회수(+)입니다. 매수·매도·계좌 안의 배당은 XIRR 현금흐름에 중복 반영하지 않습니다.</p><div className="table-wrap"><table><thead><tr><th>날짜</th><th>가족 / 계좌</th><th>구분</th><th>금액</th></tr></thead><tbody>{[...s.movements].sort((a,b)=>b.date.localeCompare(a.date)).map(f=><tr key={f.id}><td>{f.date}</td><td>{name(data.accounts.find(a=>a.id===f.account)!.owner)}<small>{accountName(f.account)}</small></td><td><span className="tag">{f.transfer?"내부이체 · ":""}{f.amount<0?"입금":"출금"}</span></td><td>{won(Math.abs(f.amount))}</td></tr>)}</tbody></table></div>{!s.movements.length&&<p className="fine">입출금 이력을 등록하면 XIRR을 계산할 수 있어요.</p>}</section>}
  </>}
  <details className="method"><summary>자료 반영과 계산 방법</summary><p>엑셀·거래내역은 ChatGPT 대화에 첨부해 주세요. 내용을 확인하고 온라인 저장소에 반영한 후 이 화면에 표시됩니다. 이 사이트는 조회 전용이며, 파일 업로드나 자료 수정은 지원하지 않습니다.</p><p>XIRR은 입금(-), 출금(+), 평가일 자산(+)으로 다시 계산하며 계좌별 수익률을 평균하지 않습니다. 연결된 내부이체는 두 계좌가 모두 선택되면 제외하고, 하나만 선택하면 입출금에 반영합니다. 모든 자료는 원화 기준입니다. 누락된 현금흐름, 여러 해가 나오는 계산, 평가 불가 상품은 수익률을 확정하지 않습니다.</p><p>배당금과 이자는 계좌에 실제 들어온 세후 금액입니다. 연금·퇴직연금·ISA처럼 현재 원천징수가 없는 계좌는 입금액 전부를 반영하고, 일반·해외계좌는 확인 가능한 원천징수 후 입금액을 반영합니다.</p><p>시세 갱신은 종목코드만 서버로 보내 Yahoo 시세와 조회 환율을 가져옵니다. 시세는 현재 화면에만 적용하며 저장된 자료는 변경하지 않습니다. 지연 가격일 수 있으며 수량·현금·계좌내역은 자동 연동하지 않습니다. 수수료·세금 등은 제공한 원가와 현금에 반영된 범위만 포함합니다.</p></details>
  <footer className="family-footer"><span>엘린하우스</span><span>함께 쌓아가는 가족의 미래</span></footer></main>
 </div>;
}
