import {describe,it,expect} from "vitest";
import {emptyPortfolio,summarize,validatePortfolio,xirr,mergePortfolio} from "./model";
import {fromCsv,parseCsv,fromWorkbookRows} from "./import";
function sample(){const p=emptyPortfolio();p.asOf="2025-01-01";p.accounts=[{id:"a",owner:"P01",broker:"은행A",name:"연금",type:"연금",mask:"",cash:100,complete:true,div:0,interest:0,realized:0},{id:"b",owner:"P02",broker:"은행B",name:"일반",type:"일반",mask:"",cash:200,complete:true,div:0,interest:0,realized:0}];p.flows=[{id:"deposit",account:"a",date:"2024-01-02",amount:-250},{id:"out",account:"a",date:"2024-06-01",amount:100,transfer:"t"},{id:"in",account:"b",date:"2024-06-01",amount:-100,transfer:"t"}];return p;}
describe("가족 자산 계산",()=>{
 it("일 년 수익률과 같은 날 상계",()=>{expect(xirr([{date:"2023-01-01",amount:-100},{date:"2024-01-01",amount:110}])).toBeCloseTo(.1,8);expect(xirr([{date:"2024-01-01",amount:-100},{date:"2024-01-01",amount:110}])).toBeNull();});
 it("손실과 복수 해를 구분",()=>{expect(xirr([{date:"2023-01-01",amount:-100},{date:"2024-01-01",amount:50}])).toBeCloseTo(-.5,8);expect(xirr([{date:"2021-01-01",amount:-100},{date:"2022-01-01",amount:230},{date:"2023-01-01",amount:-132}])).toBeNull();});
 it("가족 합산에서는 내부이체 제외, 개인과 계좌에서는 포함",()=>{const p=validatePortfolio(sample());expect(summarize(p).external).toHaveLength(1);expect(summarize(p).net).toBe(250);expect(summarize(p,"P01").net).toBe(150);expect(summarize(p,"all","b").net).toBe(100);expect(summarize(p,"all","all","은행A").nav).toBe(100);});
 it("계좌별 수익률 평균이 아닌 통합 현금흐름",()=>{const p=sample();expect(summarize(p).xirr).toBeCloseTo(.2,8);});
 it("미등록과 이력 미확인을 0%로 표시하지 않음",()=>{const p=sample();expect(summarize(p,"P03").selected).toHaveLength(0);expect(summarize(p,"P03").xirr).toBeNull();p.accounts[0].complete=false;expect(summarize(p).xirr).toBeNull();expect(summarize(p).profit).toBeNull();});
 it("혼합 ETF 분리와 미평가 상품",()=>{const p=sample();p.products.TEST={name:"혼합",price:100,exposure:[.5,0,0,0,.5]};p.holdings=[{account:"a",code:"TEST",quantity:10,cost:800}];let s=summarize(p);expect(s.equity).toBe(500);expect(s.exposure[4]).toBe(500);expect(s.nav).toBe(1300);p.products.TEST.price=null;s=summarize(p);expect(s.missing).toBe(1);expect(s.xirr).toBeNull();});
 it("중복 파일, 잘못된 내부이체, 날짜 거부",()=>{const p=sample();expect(()=>mergePortfolio(p,p)).toThrow(/중복/);p.flows[2].amount=-90;expect(()=>validatePortfolio(p)).toThrow(/내부이체/);p.flows[2].amount=-100;p.flows[0].date="2025-02-30";expect(()=>validatePortfolio(p)).toThrow(/날짜/);});
 it("CSV 인용부호와 한글·현금 중복 검증",()=>{expect(parseCsv('a,b\n"상품, A","두""개"')).toEqual([["a","b"],["상품, A",'두"개']]);const csv="기준일,계좌주,증권사,계좌명,계좌유형,현금,종목코드,상품명,수량,매입원가,원화가격,한국비중,중국비중,미국비중,기타비중,채권비중\n2025-01-01,본인,은행A,연금,연금,100,TEST,혼합,10,800,100,50,0,0,0,50";const p=fromCsv(csv);expect(summarize(p).nav).toBe(1100);expect(summarize(p).xirr).toBeNull();expect(()=>fromCsv(csv+'\n'+csv.split('\n')[1])).toThrow(/중복/);});
 it("엑셀 기말평가 중복과 전량매도 보유수량 제외",()=>{const p=fromWorkbookRows({계좌관리:[{A:"a",B:"P01",C:"은행",D:"연금",G:"2025-01-01",H:"반영",I:"10",O:"2",P:"1"},{A:"계좌주ID"},{A:"P01",B:"본인",C:"본인"}],보유자산:[{A:"a",C:"상품",D:"2",F:"50",K:"3"},{A:"a",C:"매도상품",D:"0",K:"7"}],시세배분:[{A:"상품",B:"상품",C:"123456",D:"30",F:"1",G:"0",H:"0",I:"0",J:"0"}],현금흐름:[{A:"dep",B:"2024-01-02",C:"a",E:"-50"},{A:"기말평가",B:"2025-01-01",C:"a",E:"70"}]});expect(p.flows).toHaveLength(1);expect(p.holdings).toHaveLength(1);expect(p.accounts[0].realized).toBe(10);expect(summarize(p).nav).toBe(70);});
});
